project:
  type: website
  output-dir: docs
  resources:
    - "*.pdf"
    - "*.jpg"
    - "*.png"
    - "*.svg"

website:
  title: "KAU Me-LON"
  site-url: https://www.agrinoteskau.com
  favicon: images/logo.png

  navbar:
    logo: images/logo.png
    title: "Me-LON"
    background: "#751000"
    foreground: "#ffffff"
    right:
      - href: index.qmd
        text: Home
      - href: bookshelfug.qmd
        text: Under Graduate
      - icon: github
        href: https://github.com/STATOBERRYPAPAYA/KAUMELON/issues/new
        aria-label: GitHub

  page-navigation: true
  back-to-top-navigation: true
  search: true
  reader-mode: true

  page-footer:
    border: true
    left: |
      © 2025 KAUMELON · Developed by [Dr. Pratheesh P. Gopinath](https://in.linkedin.com/in/dr-pratheesh-gopinath-aa5136212)  
      📧 [pratheesh.pg@kau.in](mailto:pratheesh.pg@kau.in) | 📞 +91 70119 04862
    center: |
      <a href="https://www.statoberry.com/papaya">![](/images/footer.png){style='height: 90px;'}</a>
    right:
      - text: RAISINS
        href: https://www.raisins.live/
      - text: KAU Grapes
        href: https://www.kaugrapes.com/
      - text: Facebook
        href: https://www.facebook.com/share/16ZrLuyTmA/?mibextid=wwXIfr

  open-graph:
    image: images/library-banner.jpg
    image-alt: "KAU Me-LON"

  twitter-card:
    image: images/library-banner.jpg
    card-style: summary_large_image

format:
  html:
    theme:
      light: [sketchy]
      dark: [darkly]
    css: style.css
    toc: true
    toc-depth: 3
    number-sections: true
    smooth-scroll: true
    code-copy: true
    highlight-style: github
    monobackgroundcolor: "#b4b58a"
    math: mathjax

editor: visual

execute:
  freeze: auto
